server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
         #          git@github.com:wangyy0721/microservicecloud-config.git
         #          https://github.com/wangyy0721/microservicecloud-config.git
          uri: https://github.com/wangyy0721/microservicecloud-config.git #GitHub上面的git仓库名字
#          search-paths: /** 
#          username: 写自己的
#          password: 写自己的
#          timeout: 1000
#          force-pull: true
 