server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
#访问地址http://myzuul.com:9527/microservicecloud-dept/dept/get/2
#加路由访问地址
zuul: 
  #ignored-services: microservicecloud-dept #忽略microservicecloud-dept真实地址
  prefix: /atguigu   #统一公共前缀   http://myzuul.com:9527/atguigu/mydept/dept/get/2
  ignored-services: "*"   #忽略所有真实地址
  routes:    #域名映射
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
 
info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

